### ISSUE TITLE
播放B站视频时，“音质音效”崩溃

### ISSUE THREAD

**Issue by MUTSUKI14444** [reiryuki/Mi-Sound-Redmi-M2012K11AC-Magisk-Module#1]
系统：K30S/MIUI13/安卓12
安装模块：AML/DTSX
崩溃场景：播放视频
具体崩溃代码如下：
android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@ff25493 -- permission denied for window type 2020
	at android.view.ViewRootImpl.setView(Unknown Source:703)
	at android.view.WindowManagerGlobal.addView(Unknown Source:207)
	at android.view.WindowManagerImpl.addView(Unknown Source:21)
	at android.app.Dialog.show(Unknown Source:194)
	at com.miui.misound.playervolume.MiuiVolumeDialogImpl$2.onShow(MiuiVolumeDialogImpl.java:258)
	at com.miui.misound.playervolume.MiuiVolumeDialogMotion.startShow(MiuiVolumeDialogMotion.java:285)
	at com.miui.misound.playervolume.MiuiVolumeDialogView.showH(MiuiVolumeDialogView.java:79)
	at com.miui.misound.playervolume.MiuiVolumeDialogImpl.showVolumeDialogH(MiuiVolumeDialogImpl.java:360)
	at com.miui.misound.playervolume.MiuiVolumeDialogImpl.showH(MiuiVolumeDialogImpl.java:331)
	at com.miui.misound.playervolume.MiuiVolumeDialogImpl.access$1600(MiuiVolumeDialogImpl.java:93)
	at com.miui.misound.playervolume.MiuiVolumeDialogImpl$H.handleMessage(MiuiVolumeDialogImpl.java:777)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)

**Comment by reiryuki** [comment]
https://t.me/androidryukimodsdiscussions/2618
If you don't do above nor using English, issues will be closed immediately in 24 hours.. Thanks you..
